/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mintic.poo.swing.cinema;

import com.mintic.poo.swing.cinema.cine.Estado;
import com.mintic.poo.swing.cinema.cine.Silla;
import com.mintic.poo.swing.cinema.cine.SillaDeshabilitada;
import com.mintic.poo.swing.cinema.cine.SillaPreferencial;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ecastrot
 */
public class FrmCinema extends javax.swing.JFrame implements ActionListener {
    
    private static ImageIcon imgSillaPreferencialReservada = new ImageIcon("D:\\cinema\\sillaPreferencialReservada.png");
    private static ImageIcon imgSillaPreferencialOcupada = new ImageIcon("D:\\cinema\\sillaPreferencialOcupada.png");
    private static ImageIcon imgSillaReservada = new ImageIcon("D:\\cinema\\sillaReservada.png");
    private static ImageIcon imgSillaOcupada = new ImageIcon("D:\\cinema\\sillaOcupada.png");
            
    /**
     * Creates new form FrmCinema
     */
    public FrmCinema() {
        initComponents();
        
        this.btnS1.addActionListener(this);
        this.btnS2.addActionListener(this);
        this.btnS3.addActionListener(this);
        this.btnS4.addActionListener(this);
        this.btnS5.addActionListener(this);
        this.btnS6.addActionListener(this);
        this.btnS7.addActionListener(this);
        this.btnS8.addActionListener(this);
        this.btnS9.addActionListener(this);
        
        crearDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnS1 = new javax.swing.JButton();
        btnS2 = new javax.swing.JButton();
        btnS3 = new javax.swing.JButton();
        btnS4 = new javax.swing.JButton();
        btnS5 = new javax.swing.JButton();
        btnS6 = new javax.swing.JButton();
        btnS7 = new javax.swing.JButton();
        btnS8 = new javax.swing.JButton();
        btnS9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnS1.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaDeshabilitada.png")); // NOI18N
        btnS1.setActionCommand("1");
        btnS1.setBorderPainted(false);
        btnS1.setContentAreaFilled(false);
        btnS1.setFocusPainted(false);

        btnS2.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaDeshabilitada.png")); // NOI18N
        btnS2.setActionCommand("2");
        btnS2.setBorderPainted(false);
        btnS2.setContentAreaFilled(false);
        btnS2.setFocusPainted(false);
        btnS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS2ActionPerformed(evt);
            }
        });

        btnS3.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaDeshabilitada.png")); // NOI18N
        btnS3.setActionCommand("3");
        btnS3.setBorderPainted(false);
        btnS3.setContentAreaFilled(false);
        btnS3.setFocusPainted(false);

        btnS4.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaLibre.png")); // NOI18N
        btnS4.setActionCommand("4");
        btnS4.setBorderPainted(false);
        btnS4.setContentAreaFilled(false);
        btnS4.setFocusPainted(false);
        btnS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS4ActionPerformed(evt);
            }
        });

        btnS5.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaLibre.png")); // NOI18N
        btnS5.setActionCommand("5");
        btnS5.setBorderPainted(false);
        btnS5.setContentAreaFilled(false);
        btnS5.setFocusPainted(false);
        btnS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS5ActionPerformed(evt);
            }
        });

        btnS6.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaLibre.png")); // NOI18N
        btnS6.setActionCommand("6");
        btnS6.setBorderPainted(false);
        btnS6.setContentAreaFilled(false);
        btnS6.setFocusPainted(false);
        btnS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS6ActionPerformed(evt);
            }
        });

        btnS7.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaPreferencialLibre.png")); // NOI18N
        btnS7.setActionCommand("7");
        btnS7.setBorderPainted(false);
        btnS7.setContentAreaFilled(false);
        btnS7.setFocusPainted(false);
        btnS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS7ActionPerformed(evt);
            }
        });

        btnS8.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaPreferencialLibre.png")); // NOI18N
        btnS8.setActionCommand("8");
        btnS8.setBorderPainted(false);
        btnS8.setContentAreaFilled(false);
        btnS8.setFocusPainted(false);
        btnS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS8ActionPerformed(evt);
            }
        });

        btnS9.setIcon(new javax.swing.ImageIcon("D:\\cinema\\sillaPreferencialLibre.png")); // NOI18N
        btnS9.setActionCommand("9");
        btnS9.setBorderPainted(false);
        btnS9.setContentAreaFilled(false);
        btnS9.setFocusPainted(false);
        btnS9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS9ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\cinema\\pantalla.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnS7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnS8)
                        .addGap(18, 18, 18)
                        .addComponent(btnS9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnS4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnS5)
                        .addGap(14, 14, 14)
                        .addComponent(btnS6)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnS1)
                        .addGap(18, 18, 18)
                        .addComponent(btnS2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnS3)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnS7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnS9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnS8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnS4)
                    .addComponent(btnS6)
                    .addComponent(btnS5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnS2)
                    .addComponent(btnS1)
                    .addComponent(btnS3))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(161, 161, 161))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnS2ActionPerformed

    private void btnS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnS4ActionPerformed

    private void btnS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnS5ActionPerformed

    private void btnS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnS6ActionPerformed

    private void btnS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnS7ActionPerformed

    private void btnS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnS8ActionPerformed

    private void btnS9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnS9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCinema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnS1;
    private javax.swing.JButton btnS2;
    private javax.swing.JButton btnS3;
    private javax.swing.JButton btnS4;
    private javax.swing.JButton btnS5;
    private javax.swing.JButton btnS6;
    private javax.swing.JButton btnS7;
    private javax.swing.JButton btnS8;
    private javax.swing.JButton btnS9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton btnSilla = (JButton) e.getSource();
        btnSilla.setIcon(imgSillaOcupada);
        System.out.println("Acción en: " + e.getActionCommand());
        
    }

    private void crearDatos() {
        Silla silla1 = new SillaDeshabilitada(1, "", Estado.DISPONIBLE);
        Silla silla2 = new SillaDeshabilitada(2, "", Estado.DISPONIBLE);
        Silla silla3 = new SillaDeshabilitada(3, "", Estado.DISPONIBLE);
        Silla silla4 = new Silla(4, "", Estado.DISPONIBLE);
        Silla silla5 = new Silla(5, "", Estado.DISPONIBLE);
        Silla silla6 = new Silla(6, "", Estado.DISPONIBLE);
        Silla silla7 = new SillaPreferencial(7, "", Estado.DISPONIBLE);
        Silla silla8 = new SillaPreferencial(8, "", Estado.DISPONIBLE);
        Silla silla9 = new SillaPreferencial(9, "", Estado.DISPONIBLE);        
    }
}

